resource_group_name = "awareson"
location            = "northeurope"
mysql_server_name   = "myappmysqlsrv"
mysql_admin         = "mysqladmin"
mysql_password      = "P@ssword1234!"
mysql_db_name       = "appdb"
acr_name            = "myappacr12345"
app_name            = "myapp-service"