resource_group_name = "awareson"
location            = "northeurope"
mysql_server_name   = "myappmysqlsrv-awareson"
mysql_admin         = "mysqladmin"
mysql_password      = "P@ssword1234!"
mysql_db_name       = "appdb-awareson"
acr_name            = "myappacr12345-awareson"
app_name            = "myapp-service-awareson"